stages:
  setup:
    cmd: bash setup.sh
    deps:
    - setup.sh
    - requirements.txt
  expand:
    cmd: bash expand_data.sh
    deps:
    - docs_dump.zip
    - expand_data.sh
    outs:
    - data
  ingest:
    cmd: python ingest.py
    params:
    - TextSplitter
    deps:
    - data
    - ingest.py
    outs:
    - docs.json
    - metadatas.json
  vectorize:
    cmd: python vector_store.py
    params:
    - OpenAIEmbeddings
    deps:
    - docs.json
    - metadatas.json
    - vector_store.py
    outs:
    - docs.index
  run:
    cmd: python qa.py
    params:
    - OpenAIEmbeddings
    - ChatOpenAI
    - Retrieval
    deps:
    - docs.index
    - ground_truths.csv
    - qa.py
    outs:
    - results.json
  eval:
    cmd: python eval.py
    deps:
    - ground_truths.csv
    - results.json
    - eval.py
    outs:
    - eval.csv
