stages:
  expand:
    cmd: bash expand_data.sh
    deps:
    - docs_dump.zip
    - expand_data.sh
    outs:
    - data
  ingest:
    cmd: python ingest.py
    params:
    - TextSplitter
    deps:
    - data
    - ingest.py
    outs:
    - docs.json
    - metadatas.json
  vectorize:
    cmd: python vector_store.py
    params:
    - OpenAIEmbeddings
    deps:
    - docs.json
    - metadatas.json
    - vector_store.py
    outs:
    - docs.index
    - faiss_store.pkl
  run:
    cmd: python qa.py
    params:
    - ChatOpenAI
    - Retrieval
    deps:
    - docs.index
    - faiss_store.pkl
    - samples.txt
    - qa.py
    outs:
    - results.csv
